modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/jeremiahwinsley/hitscan" #optional

[[mods]] #mandatory
modId="hitscan" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Hitscan" #mandatory
description='''
Adds hitscan weapons (currently just the Silver PP7).
'''

[[dependencies.hitscan]]
modId="forge"
mandatory=true
versionRange="[35,]"
ordering="NONE"
side="BOTH"

[[dependencies.hitscan]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,1.17)"
ordering="NONE"
side="BOTH"
